import { createSlice, createAsyncThunk, createEntityAdapter } from "@reduxjs/toolkit";
import { fetchPlatformsApi } from "../../api/mockApi";

// EntityAdapter gives us normalized shape: { ids: [], entities: {} }
const platformsAdapter = createEntityAdapter();

export const fetchPlatforms = createAsyncThunk(
  "platforms/fetchPlatforms",
  async () => fetchPlatformsApi()
);

const platformsSlice = createSlice({
  name: "platforms",
  initialState: platformsAdapter.getInitialState({
    status: "idle", // 'idle' | 'loading' | 'succeeded' | 'failed'
    error: null,
  }),
  reducers: {
    platformAdded: platformsAdapter.addOne,
    platformUpdated: platformsAdapter.updateOne,
    platformRemoved: platformsAdapter.removeOne,
  },
  extraReducers: (builder) => {
    builder
      .addCase(fetchPlatforms.pending, (state) => {
        state.status = "loading";
      })
      .addCase(fetchPlatforms.fulfilled, (state, action) => {
        state.status = "succeeded";
        platformsAdapter.setAll(state, action.payload);
      })
      .addCase(fetchPlatforms.rejected, (state, action) => {
        state.status = "failed";
        state.error = action.error.message;
      });
  },
});

export const { platformAdded, platformUpdated, platformRemoved } = platformsSlice.actions;

// Base selectors auto-generated by the adapter (already memoized internally)
export const platformsSelectors = platformsAdapter.getSelectors(
  (state) => state.platforms
);

export default platformsSlice.reducer;
